config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  root to: 'pages#home'
  resources :users do
    resources :bookings
  end
  resources :bookings do
    member do
      patch "update_status", to: 'bookings#update_status'
    end
    resources :user_bookings
    resources :reviews
    resources :payments
  end

  post 'booking-accepted/:id', to: 'bookings#booking_accepted', as: 'booking-accepted'
  get "dashboard", to: 'pages#dashboard'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_booking_card.html.erb
<!-- <div class="rectangle">
    <div class="first-box">
      <div class="photo-and-name">
        <% if booking.group_session == true %>
        <% end %>

        <div class="teacher name">
          <h5> <%= booking.user.first_name %> <%= booking.user.last_name %> </h5>
        </div>
      </div>
    </div>
      <div class="second-box">
        <div class="infos">
          <p>📅<%= booking.start_date %><%= booking.end_date %></p>
          <p><%= booking.user.languages.to_sentence %></p>
          <p> <%= booking.user.description %> </p>
          <p> 🏔 <%= booking.user.ski_resort %> 🏔 </p>
          <p> ❄️ <%= booking.user.categories.pluck(:name).to_sentence %> ❄️ </p>
        </div>
        <div class="price">
          <h3>Spot available:  <%= booking.available_spots %></h3>
          <div class="book-button">
            <button type="button primary" class="btn btn-primary" data-toggle="modal" data-target="#indexModal">
              + Join it
            </button>
            <div class="modal fade" id="indexModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    Modal for joining a lesson
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= link_to "Join now", new_booking_user_booking_path(booking.id)%>
        </div>
      </div>
  </div> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.facebook.com/skeasy.skeasy"><i class="fab fa-facebook"></i></a>
    <a href="https://www.instagram.com/skeasy_fr/"><i class="fab fa-instagram"></i></a>
    <a href="https://twitter.com/SkeasyF"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_group_card.html.erb
<div class="rectangle rectangle-cards">
  <div class="teacher-and-availabilities-dashboard">
    <div class="pic-name-phone">
      <div class="card-img-booking-dashboard">
        <%= cl_image_tag booking.user.photo.key, width: 200, crop: :thumb, gravity: :face %>
      </div>
      <div class="teacher-info">
        <h5> <%= booking.user.first_name %> <%= booking.user.last_name.first(1) %>. </h5>
          <% if booking.status == "Accepted" %>
            <p class="phone-number"><%= booking.user.phone_number  %></p>
          <% end %>
      </div>
    </div>
    <div class="spots-and-status">
      <div class="available-spots">
        <% if booking.group_session %>
          <% if booking.available_spots == 0 %>
            <h3> Group completed </h3>
          <% else %>
            <h3><%= booking.available_spots %> available spot(s) </h3>
          <% end %>
        <% else %>
          <h3> Private Lesson </h3>
        <% end %>
      </div>
      <div class="status-btn-<%= booking.status.downcase %> status-tag" style="text-align: center;">
        <%= booking.status %>
      </div>
    </div>
  </div>

    <div class="booking-info">
          <div class="infos" data-session="<%= booking.checkout_session_id%>">
            <div class="details">
              <p><i class="far fa-calendar-alt category-image"></i><%= booking.end_date.strftime("%B %d")%> | <%= booking.start_time.hour %>-<%= booking.end_time.hour %>h</p>
              <p>
                  <%= image_tag(booking.category + ".png", class:"category-image")%><%= booking.category %>
              </p>
              <p><i class="fas fa-mountain category-image"></i><%= booking.user.ski_resort %> </p>
                  <p><i class="far fa-comments category-image"></i><%= booking.user.languages.to_sentence %></p>
            </div>
            <%= link_to users_path , id:"backtolist" do %>
            <i class='far fa-hand-point-left '></i> Back
            <% end %>
                <div class="price text-right">
                    <% if booking.group_session == true %>
                      <div >
                        <span class="amount"><%= booking.individual_price %></span>€/person
                      </div>
                      <% if booking.status == "Accepted" %>
                        <div class='payment-btns' data-booking="<%= booking.to_json %>">
                          <%= form_tag booking_accepted_path(booking) do %>
                            <%= hidden_field_tag 'booking_id', booking.id %>
                            <%= submit_tag 'Purchase', class: 'btn btn-success btn-block my-3' %>
                          <% end %>
                        </div>
                      <% elsif booking.status == "Paid"%>
                      <% end %>
                    <% else %>
                      <div >
                          <span class="amount"><%=  booking.amount %></span>€
                      </div>
                      <% if booking.status == "Accepted" %>
                        <div class='payment-btns ' data-booking="<%= booking.to_json %>">
                          <%= form_tag booking_accepted_path(booking) do %>
                            <%= hidden_field_tag 'booking_id', booking.id %>
                            <%= submit_tag 'Purchase', class: 'btn btn-success btn-block my-3' %>
                          <% end %>
                        </div>
                      <% elsif booking.status == "Paid"%>
                      <% end %>
                    <% end %>
                </div>
                <% if booking.status == "Accepted" %>
                <%#= link_to "Go to payment", booking_path(booking), class: "btn btn-success join book-button w-100" %>
                <% end %>
        </div>
    </div>
</div>

app/views/shared/_group_card_with_review.html.erb
<div class="rectangle rectangle-cards">
    <div class="teacher-and-availabilities">
        <div class="teacher-info">
            <h5> <%= booking.user.first_name %> <%= booking.user.last_name %> </h5>
            <div class="card-img-booking">
                <%= cl_image_tag booking.user.photo.key, width: 200, crop: :thumb, gravity: :face %>
            </div>
        </div>
        <div class="available-spots">
            <h3> Done ✓</h3>
        </div>
      </div>
    <div class="booking-info">
        <div class="infos">
            <div class="modal fade" id="indexModal-<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-body">
                            <%= render 'user_bookings/new_user_booking', booking: booking, user_booking: UserBooking.new %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="details">
                <p><i class="far fa-calendar-alt category-image"></i><%= booking.end_date.strftime("%B %d")%> | <%= booking.start_time.hour %>-<%= booking.end_time.hour %>h</p>
                <p>
                    <%= image_tag(booking.category + ".png", class:"category-image") %><%= booking.category %>
                </p>
                <p><i class="fas fa-mountain category-image"></i><%= booking.user.ski_resort %> </p>
                    <p><i class="far fa-comments category-image"></i><%= booking.user.languages.to_sentence %></p>
            </div>
                <div class="price text-right">
                    <span class="amount"><%=  booking.amount %></span>€
                </div>
            <!--                   <p> <%= booking.user.description %> </p> -->
        </div>

    </div>
    <div class="btn btn-success join book-button w-100 my-3" data-toggle="modal" data-target="#NewReviewModal"> Leave a review </div>
</div>
<!-- Modal -->
<div class="modal fade" id="NewReviewModal" tabindex="-1" role="dialog" aria-labelledby="NewReviewModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Leave a review</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <%= render "reviews/new", booking: booking %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_instructor_cards.html.erb
<% current_user.bookings.upcoming.each do |instructor_booking|%>
  <%= instructor_booking.status %>
  <% instructor_booking.user_bookings.each do |user_booking|%>
    <div class="rectangle">
          <div class="first-box">
              <div class="teacher name">
                <h5> <%= user_booking.user.first_name%> <%= user_booking.user.last_name%> </h5>
              </div>
          </div>
          <div class="second-box">
            <div class="infos">
              <p> <%= user_booking.user.phone_number%> </p>
              <p>    <%= user_booking.user.category%> </p>
              <p>  <%= user_booking.user.technical_skill%></p>
              <p> <%= user_booking.participants_number%></p>
            </div>
            <div class="price">
              <%= link_to "Accept",  update_status_booking_path(user_booking.booking,params:{status: "Accepted"}), method: :patch%>
              <%= link_to "Decline",  update_status_booking_path(user_booking.booking,params:{status: "Decline"}), method: :patch%>
            </div>
          </div>
    </div>
  <% end %>
<% end %>
            
            
            
            
            
            

app/views/shared/_instructor_group_cards.erb
<% booking.user_bookings.each do |user_booking|%>
  <div class="rectangle rectangle-cards">
    <div class="teacher-and-availabilities-dashboard">
      <div class="pic-name-phone">
        <div class="card-img-booking-dashboard">
          <%= cl_image_tag user_booking.user.photo.key, width: 200, crop: :thumb, gravity: :face %>
        </div>     
        <div class="teacher-info">
          <h5> <%= user_booking.user.first_name%> <%= user_booking.user.last_name.first(1)%>. </h5>
          <% if booking.status == "Accepted" %>
            <p class="phone-number"><%= user_booking.user.phone_number%></p>
          <% end %>
        </div>
      </div>
      <div class="spots-and-status">
        <div class="available-spots">
          <% if booking.group_session %>
            <% if booking.available_spots == 0 %>
              <h3> Group completed </h3>
            <% else %>
              <h3><%= user_booking.participants_number%> Persons joined</h3>
            <% end %>
          <% else %>
            <h3> Private Lesson </h3>
          <% end %>
        </div>
        <div class="status-btn-<%= booking.status.downcase %> status-tag" style="text-align: center;">
          <%= booking.status %>
        </div>
      </div>
    </div>
    <div class="booking-info">
      <div class="infos" data-session="<%= booking.checkout_session_id%>">
        <div class="details">
          <p><i class="far fa-calendar-alt category-image"></i><%= booking.end_date.strftime("%B %d")%> | <%= booking.start_time.hour %>-<%= booking.end_time.hour %>h</p>
          <p><%= image_tag(booking.category + ".png", class:"category-image")%><%= booking.category %> | <%= user_booking.user.technical_skill%> </p>
          <p><i class="fas fa-mountain category-image"></i><%= user_booking.user.ski_resort %> </p>
          <p><i class="far fa-comments category-image"></i><%= user_booking.user.languages.to_sentence %></p>
          <div class="price text-right">
            <% if booking.group_session == true %>
              <div >
                <span class="amount"><%= booking.individual_price %></span>€/person
              </div>
            <% else %>
              <div >
                <span class="amount"><%=  booking.amount %></span>€
              </div>
            <% end %>
          </div>
            <% if  user_booking.booking.status == "Paid"%>
            <% else %>
              <% if user_booking.booking.end_date > Time.now %>
                <%= link_to "Accept", update_status_booking_path(user_booking.booking,params:{status: "Accepted"}), method: :patch, class: 'btn btn-success btn-block my-3'%>
                <%= link_to "Decline", update_status_booking_path(user_booking.booking,params:{status: "Rejected"}), method: :patch, class: 'btn btn-success btn-block my-3'%>
              <% else %>
              <% end %>
            <% end %>
        </div>
          <%= link_to users_path , id:"backtolist" do %>
            <i class='far fa-hand-point-left '></i> Back to teachers
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= SKEASY %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%if current_user.photos.present?%>
          <%=  cl_image_tag current_user.photos.first.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%=  image_tag ("logo.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <%= current_user.first_name %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete,  class: "dropdown-item"%>

          </div>
        </li>
        <li class="nav-item-language">
        </li>
      <% else %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Login      | ", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item-language">
            <%= link_to "Create an account      | ", new_user_registration_path, class: "nav-link" %>
            <%# <%= link_to "En ", class: "nav-link" %>
            <%# <i class="fas fa-chevron-down"></i> %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_teacher_card.html.erb
<%= link_to user_path(teacher) do %>
<div class="card-teacher">
    <div class="card-img">
        <% if teacher.photos.attached? %>
        <%= cl_image_tag teacher.photos.first.key, width: 200, crop: :thumb, gravity: :face %>
        <% end %>
    </div>
    <div class="card-info">


        <h2 id="first-name"><%= teacher.first_name %></h2>
        <h2 id="last-name"><%= teacher.last_name %></h2>
        <p id="stars">
            <%if teacher.average_rating.present? %>
              <% teacher.average_rating.times do %>
              <i class="fas fa-star"></i>
              <% end %>
            <% end %>
        </p>
        <% teacher.categories.each do |categorie| %>
        <%= image_tag(categorie.name + ".png", class:"category-image") %>
        <% end %>

        <!-- <img src="<%=teacher.categories.pluck(:name).to_sentence%>.jpg" alt=""> -->
        <p id="category"> <%= teacher.categories.pluck(:name).to_sentence %> </p>
        <% if teacher.description.present? %>
          <p id="description"><i class="fas fa-quote-left mr-2"></i><%= teacher.description.truncate(90)%><i class="fas fa-quote-right ml-2"></i></p>
        <% else %>
          <%= "Fuck off" %>
        <% end %>
        <p id="ressort"> <i class="fas fa-mountain mr-2"> </i><%= teacher.ski_resort %> </p>
        <p id="languages"> <i class="far fa-comments mr-2"> </i><%= "#{teacher.languages.to_sentence}" %> </p>
    </div>
</div>
<% end %>